import React from "react";

const WhatsAppAutomationInstructions: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto pr-8 space-y-8">
      
      {/* Header */}
      <div>
        <h1 className="text-2xl font-semibold text-gray-900">
          WhatsApp Communication 
        </h1>
        <p className="text-sm text-gray-600 mt-1">
          Below describes how WhatsApp messaging works within the CRM system.
        </p>
      </div>

      {/* Automation Status */}
      <div className="border rounded-xl p-6 bg-green-50 border-green-300">
        <div className="flex justify-between items-center">
          <h2 className="text-lg font-semibold text-green-800">
            Automation Status
          </h2>
          <span className="bg-green-600 text-white text-xs px-3 py-1 rounded-full">
            ENABLED
          </span>
        </div>

        <p className="text-sm text-green-800 mt-3">
          WhatsApp message responses are automatically generated by the system.
          Incoming customer messages trigger predefined backend workflows
          that send system-defined replies.
        </p>
      </div>

      {/* How It Works */}
      <div className="border rounded-xl p-6 border-gray-200">
        <h3 className="text-lg font-semibold text-gray-800 mb-3">
          Message Processing Flow
        </h3>

        <ol className="list-decimal list-inside text-sm text-gray-700 space-y-2">
          <li>
            A customer sends a message to the connected WhatsApp number.
          </li>
          <li>
            The message is received by the CRM backend via webhook integration.
          </li>
          <li>
            The system evaluates the message based on predefined automation logic.
          </li>
          <li>
            A system-generated response is sent automatically.
          </li>
          <li>
            Based on user responses, a Lead or Support Ticket may be created.
          </li>
        </ol>
      </div>

      {/* Restriction Section */}
      <div className="border rounded-xl p-6 bg-yellow-50 border-yellow-300">
        <h3 className="text-lg font-semibold text-yellow-800 mb-2">
          Manual Messaging Disabled
        </h3>

        <p className="text-sm text-yellow-800">
          CRM users cannot manually compose, send, or reply to WhatsApp messages
          from within this system.
        </p>

        <p className="text-sm text-yellow-800 mt-2">
          There is no chat interface or manual message input available.
          All responses are fully automated and controlled by backend workflows.
        </p>
      </div>

      {/* Footer Note */}
      <div className="text-xs text-gray-500">
        WhatsApp messaging functionality operates in accordance with Meta platform policies.
      </div>
    </div>
  );
};

export default WhatsAppAutomationInstructions;