type SupportTicketProps = {
    count? : number ,
    id : number ,
    ticketNumber: string,
    companyId : number ,
    accountName : string,
    accountEmail : string,
    accountMobileNumber: string,
    companyProductName : string,
    barcode : string,
    serialNumber : string,
    accountCompanyProductId : number ,
    supportTicketCategoryId : number ,
    supportTicketCategoryName : string ,
    supportTicketEscalationLevelId : number ,
    supportTicketEscalationLevelName : string ,
    supportTicketLifecycleId : number,
    supportTicketLifecycleName : string,
    companyProductSlaId : number,
    companyProductSlaName : string,
    supportTicketSourceId : number,
    supportTicketSourceName : string,
    queryDescription? : string,
    publicNotes? : string,
    resolutionApplied : string,
    assignedTo : number,
    assignedToName : string,
    resolvedBy : number,
    resolvedByName : string,
    dueDateTime : string,
    completedAtDateTime : string,
    createdBy : string ,
    createdOn : string ,
    updatedBy? : string ,
    updatedOn? : string ,
}
export default SupportTicketProps;