export const COLORS={
    PRIMARY_BUTTON_BLUE_COLOR:"bg-blue-600",
    PRIMARY_BUTTON_BLUE_COLOR_HOVER:"hover:bg-blue-700",
    PRIMARY_SNACKBAR_TEXT_GREEN_COLOR:"text-green-800",
    PRIMARY_SNACKBAR_TEXT_RED_COLOR:"text-red-800",
}


export const PAGINATION={
    DROPDOWN_OPTION_FOR_COMPANY_USER_PAGINATION:[15,10,5],
    PAGINATION_COMPANY_USER_DEFAULT_SIZE:15
}