import { Lead } from "../@types/lead-management/LeadManagementProps";

export const productsData = [
    {
      productName : "Product 1",
      itemCode: "ABC121",
      description:
        "Product 1 of XYZ Company which is for sell and marketing purpose",
      price: 10.99,
      HSN: "xxCode1xx",
      SAC: "xxCode1xx",
    },
    {
      productName : "Product 2",
      itemCode: "ABC122",
      description:
        "Product 2 of XYZ Company which is for sell and marketing purpose",
      price: 13.85,
      HSN: "xxCode2xx",
      SAC: "xxCode2xx",
    },
    {
      productName : "Product 3",
      itemCode: "ABC123",
      description:
        "Product 3 of XYZ Company which is for sell and marketing purpose",
      price: 20.34,
      HSN: "xxCode3xx",
      SAC: "xxCode3xx",
    },
    {
      productName : "Product 4",
      itemCode: "ABC124",
      description:
        "Product 4 of XYZ Company which is for sell and marketing purpose",
      price: 11.53,
      HSN: "xxCode4xx",
      SAC: "xxCode4xx",
    },
    {
      productName : "Product 5",
      itemCode: "XYZ567",
      description: "Product 5 description",
      price: 15.99,
      HSN: "xxCode5xx",
      SAC: "xxCode5xx",
    },
    {
      productName : "Product 6",
      itemCode: "PQR890",
      description: "Product 6 description",
      price: 22.5,
      HSN: "xxCode6xx",
      SAC: "xxCode6xx",
    },
    {
      productName : "Product 7",
      itemCode: "LMN123",
      description: "Product 7 description",
      price: 9.75,
      HSN: "xxCode7xx",
      SAC: "xxCode7xx",
    },
    {
      productName : "Product 8",
      itemCode: "STU456",
      description: "Product 8 description",
      price: 18.2,
      HSN: "xxCode8xx",
      SAC: "xxCode8xx",
    },
    {
      productName : "Product 9",
      itemCode: "EFG789",
      description: "Product 9 description",
      price: 12.35,
      HSN: "xxCode9xx",
      SAC: "xxCode9xx",
    },
     {
      productName : "Product 10",
      itemCode: "HIJ012",
      description: "Product 10 description",
      price: 25.8,
      HSN: "xxCode10xx",
      SAC: "xxCode10xx",
    },
     {
      productName : "Product 11",
      itemCode: "KLM345",
      description: "Product 11 description",
      price: 14.65,
      HSN: "xxCode11xx",
      SAC: "xxCode11xx",
    },
     {
      productName : "Product 12",
      itemCode: "NOP678",
      description: "Product 12 description",
      price: 21.9,
      HSN: "xxCode12xx",
      SAC: "xxCode12xx",
    },
     {
      productName : "Product 13",
      itemCode: "QRS901",
      description: "Product 13 description",
      price: 10.5,
      HSN: "xxCode13xx",
      SAC: "xxCode13xx",
    },
     {
      productName : "Product 14",
      itemCode: "TUV234",
      description: "Product 14 description",
      price: 17.75,
      HSN: "xxCode14xx",
      SAC: "xxCode14xx",
    },
     {
      productName : "Product 15",
      itemCode: "WXY567",
      description: "Product 15 description",
      price: 23.1,
      HSN: "xxCode15xx",
      SAC: "xxCode15xx",
    },
     {
      productName : "Product 16",
      itemCode: "ZAB890",
      description: "Product 16 description",
      price: 11.85,
      HSN: "xxCode16xx",
      SAC: "xxCode16xx",
    },
    {
      productName : "Product 17",
      itemCode: "CDE123",
      description: "Product 17 description",
      price: 19.5,
      HSN: "xxCode17xx",
      SAC: "xxCode17xx",
    },
    {
      productName : "Product 18",
      itemCode: "FGH456",
      description: "Product 18 description",
      price: 16.25,
      HSN: "xxCode18xx",
      SAC: "xxCode18xx",
    },
    {
      productName : "Product 19",
      itemCode: "IJK789",
      description: "Product 19 description",
      price: 24.9,
      HSN: "xxCode19xx",
      SAC: "xxCode19xx",
    }
  ];



export const ProductsRadioButtonOptions = [
  {
    label : "HSN",
    value : "HSN",
    id : "HSN",
    name : "taxCode",
    checked : false,
  },
  {
    label : "SAC",
    value : "SAC",
    id : "SAC",
    name : "taxCode",
    checked : false,
  },
  {
    label : "All",
    value : "All",
    id : "all",
    name : "taxCode",
    checked : false,
  }

]

export const leadsData:Lead[] = [
  {
    id: 1,
    leadNo: "Lead-9500",
    name: "Mr. Ghorpade",
    email: "ghorpade@example.com",
    phone: "8624003552",
    remark: "Information given, price pitched 18k. Client will let us know.",
    status: "Open",
    createdOn: "Feb 17, 2025 10:53:26",
    updatedOn: "Feb 17, 2025 10:53:26",
    createdBy: "Suraj Darade",
    updatedBy: "Suraj Darade",
    assignedTo: "Suraj Darade",
    source: "Marketing"
  },
  {
    id: 2,
    leadNo: "Lead-9499",
    name: "Mr. Samadhan Tonde",
    email: "samadhan.tonde@example.com",
    phone: "8956024594",
    remark: "Client interested, discussing budget.",
    status: "Open",
    createdOn: "Feb 15, 2025 18:26:32",
    updatedOn: "Feb 15, 2025 18:26:32",
    createdBy: "Suraj Darade",
    updatedBy: "Suraj Darade",
    assignedTo: "Suraj Darade",
    source: "Marketing"
  },
  {
    id: 3,
    leadNo: "Lead-9498",
    name: "Mr. Ashok Rathi",
    email: "ashok.rathi@example.com",
    phone: "7791079777",
    remark: "Information given, price pitched 28k 37k.",
    status: "Open",
    createdOn: "Feb 15, 2025 17:35:55",
    updatedOn: "Feb 15, 2025 17:35:55",
    createdBy: "Suraj Darade",
    updatedBy: "Suraj Darade",
    assignedTo: "Suraj Darade",
    source: "Marketing"
  },
  {
    id: 4,
    leadNo: "Lead-9497",
    name: "Mr. Tarun Chavda",
    email: "tarun.chavda@example.com",
    phone: "7984671703",
    remark: "Client is not receiving the call.",
    status: "Open",
    createdOn: "Feb 17, 2025 10:35:54",
    updatedOn: "Feb 17, 2025 10:35:54",
    createdBy: "Suraj Darade",
    updatedBy: "Suraj Darade",
    assignedTo: "Suraj Darade",
    source: "Marketing"
  },
  {
    id: 5,
    leadNo: "Lead-9496",
    name: "Mr. Nilesh Gaikwad",
    email: "nilesh.gaikwad@example.com",
    phone: "9824850726",
    remark: "Client said he will callback after speaking with his senior.",
    status: "Open",
    createdOn: "Feb 17, 2025 10:53:26",
    updatedOn: "Feb 17, 2025 10:53:26",
    createdBy: "Pravin Whatkar",
    updatedBy: "Pravin Whatkar",
    assignedTo: "Pravin Whatkar",
    source: "Marketing"
  },
  {
    id: 6,
    leadNo: "Lead-9463",
    name: "Mr. Vishal",
    email: "vishal@example.com",
    phone: "9960622953",
    remark: "Information given, price pitched 18k. Client said he will let us know.",
    status: "Open",
    createdOn: "Feb 15, 2025 18:27:12",
    updatedOn: "Feb 15, 2025 18:27:12",
    createdBy: "Pravin Whatkar",
    updatedBy: "Pravin Whatkar",
    assignedTo: "Pravin Whatkar",
    source: "Marketing"
  },
  {
    id: 7,
    leadNo: "Lead-9462",
    name: "Mr. Vishal Sature",
    email: "vishal.sature@example.com",
    phone: "7304312332",
    remark: "Information given, price pitched 28k.",
    status: "Open",
    createdOn: "Feb 14, 2025 13:39:41",
    updatedOn: "Feb 14, 2025 13:39:41",
    createdBy: "Pravin Whatkar",
    updatedBy: "Pravin Whatkar",
    assignedTo: "Pravin Whatkar",
    source: "Marketing"
  },
  {
    id: 8,
    leadNo: "Lead-9461",
    name: "Mr. Bharat Kumar",
    email: "bharat.kumar@example.com",
    phone: "8849362576",
    remark: "Information given, price pitched 18k.",
    status: "Open",
    createdOn: "Feb 14, 2025 13:39:41",
    updatedOn: "Feb 14, 2025 13:39:41",
    createdBy: "Pravin Whatkar",
    updatedBy: "Pravin Whatkar",
    assignedTo: "Pravin Whatkar",
    source: "Marketing"
  },
  {
    id: 9,
    leadNo: "Lead-9460",
    name: "Mr. Vishal More",
    email: "vishal.more@example.com",
    phone: "8832032078",
    remark: "Client requested follow-up next week.",
    status: "Open",
    createdOn: "Feb 12, 2025 18:37:18",
    updatedOn: "Feb 12, 2025 18:37:18",
    createdBy: "Pravin Whatkar",
    updatedBy: "Pravin Whatkar",
    assignedTo: "Pravin Whatkar",
    source: "Marketing"
  },
  {
    id: 10,
    leadNo: "Lead-9517",
    name: "Mr. Pankaj Yadav",
    email: "pankaj.yadav@example.com",
    phone: "9888776655",
    remark: "Exploring options, requested price list.",
    status: "Open",
    createdOn: "Feb 16, 2025 18:00:50",
    updatedOn: "Feb 16, 2025 18:00:50",
    createdBy: "Sandeep Reddy",
    updatedBy: "Sandeep Reddy",
    assignedTo: "Sandeep Reddy",
    source: "LinkedIn"
  }
]


export const interest = []


 