type LeadImportDataType = {
    additional_contact_number: string,
    address:string,
    company_id:number,
    count:number,
    country_id: number,
    country_name:string,
    createdby_name : string,
    createdon : string,
    district_id : number,
    district_name : string,
    email : string
    id : number,
    import_tag : string,
    industry_name : string,
    job_title : string,
    lead_owner : string
    lead_source : string,
    lead_source_id : number,
    lead_status : string,
    lead_status_id : number,
    mobilenumber : string,
    name : string,
    ownerid : number,
    state_id : number,
    state_name : string,
    updatedby_name : string,
    updatedon : string,
    website : string,
    lead_interest : string,
    lead_interest_id : number,
    company_product_id : number,
    company_product_name : string,
    lead_created_on : string,
    description : string,

}
export default LeadImportDataType;