type LeadDetailsData={
    id: number,
    lead_id: number,
    country_id: number,
    country_name: string,
    district_id: number,
    district_name: string,
    state_id: number,
    state_name: string,
    address: string,
    industry_type_id: number,
    industry_type: string,
    industry_name: string,
    job_title: string,
    website: string,
    additional_contact_number: string,
    createdby: string,
    createdon: string,
    updatedby: string,
    updatedon: string
    // additional_contact_number: string,
    // address: "",
    // country_id: 0,
    // country_name: "",
    // createdby: "",
    // createdon: "",
    // district_id: 0,
    // district_name: "",
    // id: 0,
    // industry_name: "",
    // industry_type: "",
    // industry_type_id: 0,
    // job_title: "",
    // lead_id: 0,
    // state_id: 0,
    // state_name: "",
    // updatedby: "",
    // updatedon: "",
    // website: "",
}

export default LeadDetailsData;